language: java

sudo: required

jdk:
  - oraclejdk8

notifications:
    email: false

before_install:
    - wget http://services.gradle.org/distributions/gradle-4.5.1-bin.zip
    - unzip gradle-4.5.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.5.1
    - export PATH=$GRADLE_HOME/bin:$PATH
